id: P010714
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:10.467718
source_metadata:
  id: bdr:W3CN4636
  title: སྡོམ་གསུམ་རྣམ་ངེས་ཀྱི་འགྲེལ་པ་དང་སྡོམ་པ་གསུམ་གྱི་རྣམ་བཞག་མདོར་བསྡུས་པ།
  author: ''
  volumes:
    3ae8a3a5a1c948ae897a477d38ef4e7e:
      image_group_id: I3CN4638
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
