id: P010714
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4636
  title: སྡོམ་གསུམ་རྣམ་ངེས་ཀྱི་འགྲེལ་པ་དང་སྡོམ་པ་གསུམ་གྱི་རྣམ་བཞག་མདོར་བསྡུས་པ།
  author: ''
  volumes:
    3ae8a3a5a1c948ae897a477d38ef4e7e:
      image_group_id: I3CN4638
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
